//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dentist2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class helpdesk
    {
        public int id { get; set; }
        public string location { get; set; }
        public string logo { get; set; }
        public string aboutext { get; set; }
        public string fblink { get; set; }
        public string instalink { get; set; }
        public string twitlink { get; set; }
        public string dentalemergancyphto { get; set; }
        public string dentalemergancytext { get; set; }
        public string mapsource { get; set; }
    }
}
