//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dentist2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class medicalEntities : DbContext
    {
        public medicalEntities()
            : base("name=medicalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<About> Abouts { get; set; }
        public virtual DbSet<contact> contacts { get; set; }
        public virtual DbSet<gallery> galleries { get; set; }
        public virtual DbSet<helpdesk> helpdesks { get; set; }
        public virtual DbSet<icon> icons { get; set; }
        public virtual DbSet<news> news { get; set; }
        public virtual DbSet<openinghour> openinghours { get; set; }
        public virtual DbSet<range> ranges { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<subscribe> subscribes { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<team> teams { get; set; }
        public virtual DbSet<slide> slides { get; set; }
    }
}
