//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dentist2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class openinghour
    {
        public int id { get; set; }
        public string startday { get; set; }
        public string andday { get; set; }
        public System.TimeSpan starttime { get; set; }
        public System.TimeSpan andtime { get; set; }
    }
}
